name: .NET
on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: build native lib
      uses: devbotsxyz/xcode-build@v1.0.0
      with:
        workspace: native
        project: darwinlog
        configuration: release
    - name: Restore dependencies
      run: dotnet restore DarwinLog/DarwinLog.csproj
    - name: Build
      run: dotnet build DarwinLog/DarwinLog.csproj --no-restore
    - name: Pack
      run: dotnet pack DarwinLog/DarwinLog.csproj --no-build
    - name: Publish Nuget
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        PROJECT_FILE_PATH: DarwinLog/DarwinLog.csproj
        NUGET_KEY: ${{ secrets.NUGETAPIKEY }}
      
