name: .NET
on:
  push:
    branches: [ main ]
    paths:
      - DarwinLog/*
      - native/*

jobs:
  buildAndRelease:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: build native lib
      uses: devbotsxyz/xcode-build@v1.0.0
      with:
        project: native/darwinlog.xcodeproj
        configuration: Release
    - name: Restore dependencies
      run: dotnet restore DarwinLog/DarwinLog.csproj
    - name: Build
      run: dotnet build DarwinLog/DarwinLog.csproj -c Release --no-restore
    - name: Pack
      run: dotnet pack DarwinLog/DarwinLog.csproj -c Release --no-build
    - name: upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: nuget
        path: DarwinLog/bin/**/*.nupkg
    - name: Publish Nuget
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        PROJECT_FILE_PATH: DarwinLog/DarwinLog.csproj
        NUGET_KEY: ${{ secrets.NUGETAPIKEY }}
      
      
